Validate BT device name to be among known from configuration file.

diff --git a/trunk/src/bt/bt-connector b/trunk/src/bt/bt-connector
--- a/trunk/src/bt/bt-connector
+++ b/trunk/src/bt/bt-connector
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-#  Copyright 2007-2022 Alex Vesev
+#  Copyright 2007-2025 Alex Vesev
 #
 #  This file is part of Script Crypt.
 #
@@ -66,6 +66,15 @@ function ask_for_bt_wake_up {
         then
             trigger-bt-state --switch ${OPT_VERBOSE:-}
         fi
+    fi
+}
+
+function check_if_is_known_dev {
+    local dev_conf_name="${1?Device name from configuration file is not specified.}"
+    if [[ ! -v device_mac_pool["${dev_conf_name}"] ]] ; then
+        set +x
+        echo "ERROR:${0}:${LINENO}: Unknown device '${dev_conf_name}' for configuration file '${file_cnf}'. See '${0}' --help" >&2
+        exit 1
     fi
 }
 
@@ -150,6 +159,7 @@ while [ ${#} -gt 0 ] ; do
             ;;
         -n|--name)
             d_name="${arg_value}"
+            check_if_is_known_dev "${d_name:-}"
             ;;
         -c|--connect)
             if [ ! -v op_name ] ; then
