System wide Bluetooth switcher configuration installation workflow.

diff --git a/trunk/src/bt/bt-connector b/trunk/src/bt/bt-connector
--- a/trunk/src/bt/bt-connector
+++ b/trunk/src/bt/bt-connector
@@ -85,8 +85,10 @@ if [ "${*}" != "${*/--install/}" ] ; then
     declare -r file_this="${0}"
     declare -r file_cnf="$( getent passwd "$owner" | cut -d: -f6 )/.config/bt-connector/conf.json"
 
-    install --mode 755 --owner=root --group=root "${file_this}" /usr/bin
-    if [ ! -d "/etc/bt-connector" ] ; then
+    if [ "${file_this}" != "/usr/bin/$( basename "${file_this}" )" ] ; then
+        install --mode 755 --owner=root --group=root "${file_this}" /usr/bin
+    fi
+    if [ ! -f "/etc/bt-connector/conf.json" ] ; then
         install --directory --mode 755 --owner=root --group=root /etc/bt-connector/
         cat << EOF > /etc/bt-connector/conf.json
 {
@@ -97,7 +99,7 @@ if [ "${*}" != "${*/--install/}" ] ; then
 }
 EOF
         chmod 644       /etc/bt-connector/conf.json
-        chown root.root /etc/bt-connector/conf.json
+        chown root:root /etc/bt-connector/conf.json
     fi
     if [ ! -f "${file_cnf}" ] ; then
         install --mode 755 --owner="${owner}" --group="${owner}" --directory "$( dirname "${file_cnf}" )"
@@ -107,13 +109,20 @@ EOF
 fi
 
 if [ "${*}" != "${*/--conf-file/}" ] ; then
+    set +x
     echo "ERROR:${0}:${LINENO}: Unimplemented functionality call." >&2
     exit 1
 else
     if [ -f ~/.config/bt-connector/conf.json ] ; then
-        declare -r file_cnf=~/.config/bt-connector/conf.json
+        declare -r file_cnf="${HOME}/.config/bt-connector/conf.json"
     else
-        declare -r file_cnf=/etc/bt-connector/conf.json
+        if [ -f /etc/bt-connector/conf.json ] ; then
+            declare -r file_cnf=/etc/bt-connector/conf.json
+        else
+            set +x
+            echo "ERROR:$( basename "${0}" ):${LINENO}: Missed configuration file '/etc/bt-connector/conf.json'. You may try 'sudo \"${0}\" --install' to create the file." >&2
+            exit 1
+        fi
     fi
 fi
 
@@ -209,4 +218,3 @@ fi
 
 set +x
 echo "INFO:${0}:${LINENO}: Job done." >&2
-echo "" >&2
